apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd-system
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: applicazioni
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 50.3.1
    chart: kube-prometheus-stack
    path: monitoring
    helm:
      valueFiles:
      - values-dev.yaml
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - ServerSideApply=true