apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fclinica-2023.fullname" . }}-env
data:
  .env: |-
    APP_NAME=Fclinica
    APP_ENV=local
    APP_KEY=base64:MlV4dHfQAWTDUGlduNzbMdhG5FSRta5zrywz0VOK6/8=
    APP_DEBUG=true
    APP_URL=http://localhost
    APP_URL_BASE=fclinica.it
    BACKPACK_REGISTRATION_OPEN=false

    LOG_CHANNEL=single
    LOG_DEPRECATIONS_CHANNEL=null
    LOG_LEVEL=debug

    BROADCAST_DRIVER=log
    CACHE_DRIVER=redis
    FILESYSTEM_DISK=local
    QUEUE_CONNECTION=redis
    SESSION_DRIVER=redis
    SESSION_LIFETIME=120

    MAIL_MAILER=smtp
    MAIL_HOST=smtp.mailtrap.io
    MAIL_PORT=2525
    MAIL_USERNAME="3079bd59135615"
    MAIL_PASSWORD="448226f2a80ceb"
    MAIL_ENCRYPTION=null
    MAIL_FROM_ADDRESS="{{ include "fclinica-2023.fullname" . }}@example.com"
    MAIL_FROM_NAME="${APP_NAME}"

{{ if .Values.mysql.enabled }}
    DB_CONNECTION=mysql
    DB_HOST={{ include "fclinica-2023.fullname" . }}-mysql-primary
    DB_PORT=3306
    DB_DATABASE={{ .Values.mysql.auth.database }}
    DB_USERNAME={{ .Values.mysql.auth.username }}
    DB_PASSWORD={{ .Values.mysql.auth.password }}
{{ end }}

{{ if .Values.redis.enabled }}
    REDIS_HOST={{ include "fclinica-2023.fullname" . }}-redis-master
    REDIS_PASSWORD={{ .Values.redis.global.redis.password }}
    REDIS_PORT=6379
{{ end }}

{{ if .Values.s3.enabled }}
    AWS_ACCESS_KEY_ID={{ .Values.s3.access_key }}
    AWS_SECRET_ACCESS_KEY={{ .Values.s3.secret_key }}
    AWS_BUCKET={{ .Values.s3.bucket }}
    AWS_USE_PATH_STYLE_ENDPOINT={{ .Values.s3.path_style }}
    AWS_ENDPOINT={{ .Values.s3.endpoint }}
{{ end }}

{{ if .Values.stripe.enabled }}
    STRIPE_KEY=pk_test_znlFgsvQATvNVKv39Rt4Ep0K0000wYV4Vw
    STRIPE_SECRET=sk_test_socy8nxqBv3G6xjaSe2lW8I900KOq8XbiB
    STRIPE_WEBHOOK_SECRET=uplift-cheer-safe-upbeat
    CASHIER_CURRENCY=eur
    CASHIER_CURRENCY_LOCALE=it_IT
{{ end }}
