{{- if .Values.fclinica.IngressRouteTCP.enabled -}}
{{- $fullName := include "fclinica-2023.fullname" . -}}

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ $fullName }}
spec:
  entryPoints:
    - websecure
  routes:
    {{- range .Values.fclinica.IngressRouteTCP.hosts }}
  - match: HostSNI({{ .host | quote }})
    services:
    - name: {{ $fullName }}
      port: 443
    {{- end }}
  tls:
    passthrough: true
  
{{- end }}
