apiVersion: v1
kind: Service
metadata:
  name: {{ include "fclinica-2023.fullname" . }}
  labels:
    {{- include "fclinica-2023.labels" . | nindent 4 }}
spec:
  type: {{ .Values.fclinica.service.type }}
  ports:
    {{- range .Values.fclinica.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "fclinica-2023.selectorLabels" . | nindent 4 }}
