apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd-system
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: applicazioni
  source:
    chart: kube-prometheus-stack
    path: monitoring
    repoURL: https://helm.goharbor.io
    targetRevision: 1.13.0
    helm:
      valueFiles:
      - values.yaml
  syncPolicy:
    automated:
      selfHeal: true