apiVersion: v1
data:
  admin-password: PWR2JVlOLihRcVc1cG5mOGp+Cg==
  admin-user: RmcwMjEwODAhCg==
  ldap-toml: ""
kind: Secret
metadata:
  name: monitoring-grafana
  namespace: monitoring
type: Opaque