apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd-system
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: applicazioni
  source:
    - chart: cert-manager
      helm:
        parameters:
        - name: installCRDs
          value: "true"
      repoURL: https://charts.jetstack.io
      targetRevision: v1.12.4
    - repoURL: https://github.com/Gjonni/k3s.git
      ref: values
      path: cert-manager

  syncPolicy:
    automated:
      selfHeal: true