apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd-system
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: applicazioni
  sources:
    - chart: cert-manager
      helm:
        parameters:
        - name: installCRDs
          value: "true"
      repoURL: https://charts.jetstack.io
      targetRevision: v1.13.2
    - repoURL: https://github.com/Gjonni/k3s.git
      path: cert-manager
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true