apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd-system
spec:
  destination:
    namespace: harbor-system
    server: https://kubernetes.default.svc
  project: applicazioni
  sources:
    - chart: harbor
      repoURL: https://helm.goharbor.io
      targetRevision: 1.13.1
      helm:
        valueFiles:
        - $values/harbor/values.yaml
    - repoURL: https://github.com/Gjonni/k3s.git
      ref: values
      path: harbor
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true