apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd-system
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: applicazioni
  sources:
    - chart: kube-prometheus-stack
      repoURL:  https://prometheus-community.github.io/helm-charts
      targetRevision: 51.1.1
      helm:
        valueFiles:
        - $values/monitoring/values.yaml
    - repoURL: https://github.com/Gjonni/k3s.git
      ref: values
      path: monitoring
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - ServerSideApply=true