apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: phpmyadmin
  namespace: argocd-system
spec:
  destination:
    namespace: tools-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: phpmyadmin
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.1.0
  syncPolicy:
    automated:
      selfHeal: true