apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd-system
spec:
  destination:
    namespace: harbor-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: harbor
    path: harbor
    repoURL: https://helm.goharbor.io
    targetRevision: 1.13.0
    helm:
      valueFiles:
      - values.yaml
  syncPolicy:
    automated:
      selfHeal: true