apiVersion: batch/v1
kind: CronJob
metadata:
  name: prenota-lezioni
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: prenota-lezioni-inglese
              image: harbor.k3s.filice.eu/library/inglese:latest
              envFrom:
              - secretRef:
                  name: partec-secrets
