apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: backup-fclinica
  namespace: velero
spec:
  paused: true
  schedule: 5 4 * * *
  template:
    csiSnapshotTimeout: 0s
    hooks: {}
    includedNamespaces:
    - fclinica
    itemOperationTimeout: 0s
    metadata: {}
    ttl: 168h0m0s
  useOwnerReferencesInBackup: false
