apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: backup-passbolt
  namespace: velero
spec:
  paused: false
  schedule: 0 0 * * *
  template:
    csiSnapshotTimeout: 0s
    hooks: {}
    includedNamespaces:
    - passbolt
    itemOperationTimeout: 0s
    metadata: {}
    ttl: 168h0m0s
  useOwnerReferencesInBackup: false